// View Actions
export const START_TRANSITION = 'START_TRANSITION';
export const PERSIST_TRANSITION = 'PERSIST_TRANSITION';
export const COMPLETE_TRANSITION = 'COMPLETE_TRANSITION';
export const TOGGLE_DELETION = 'TOGGLE_DELETION';

// Array Actions
export const ADD_TO_ARRAY = 'ADD_TO_ARRAY';
export const DELETE_FROM_ARRAY = 'DELETE_FROM_ARRAY';
export const UPDATE_PATH = 'UPDATE_PATH';

// Stack Actions
export const EXPAND_STACK = 'EXPAND_STACK';
export const COLLAPSE_STACK = 'COLLAPSE_STACK';
export const ADD_TO_STACK = 'ADD_TO_STACK';
export const REMOVE_FROM_STACK = 'REMOVE_FROM_STACK';
export const INSERT_STACK = 'INSERT_STACK';
export const CLEAR_STACK = 'CLEAR_STACK';